##################################################################################################

python -u run.py --is_training 1 --model_id heat1 --model MetaTCN --root_path ./all_six_datasets/heat/ --data_path heath1.csv --data custom --features M --seq_len 12 --pred_len 6 --label_len 0 --ffn_ratio 8 --patch_size 8 --patch_stride 4 --num_blocks 1 --large_size 51 --small_size 5 --dims 256 256 256 256 --head_dropout 0.0 --enc_in 8 --dropout 0.3 --itr 1 --train_epochs 20 --batch_size 256 --patience 20 --learning_rate 0.0001 --des Exp --use_multi_scale False --small_kernel_merged False --type_model 2 --num_extract_blocks 1 --num_memory 1

python -u run.py --is_training 1 --model_id heat1 --model MetaTCN --root_path ./all_six_datasets/heat/ --data_path heath1.csv --data custom --features M --seq_len 24 --pred_len 12 --label_len 0 --ffn_ratio 8 --patch_size 8 --patch_stride 4 --num_blocks 1 --large_size 51 --small_size 5 --dims 256 256 256 256 --head_dropout 0.0 --enc_in 8 --dropout 0.3 --itr 1 --train_epochs 20 --batch_size 256 --patience 20 --learning_rate 0.0001 --des Exp --use_multi_scale False --small_kernel_merged False --type_model 2 --num_extract_blocks 1 --num_memory 1

python -u run.py --is_training 1 --model_id heat1 --model MetaTCN --root_path ./all_six_datasets/heat/ --data_path heath1.csv --data custom --features M --seq_len 38 --pred_len 18 --label_len 0 --ffn_ratio 8 --patch_size 8 --patch_stride 4 --num_blocks 1 --large_size 51 --small_size 5 --dims 256 256 256 256 --head_dropout 0.0 --enc_in 8 --dropout 0.3 --itr 1 --train_epochs 20 --batch_size 256 --patience 20 --learning_rate 0.0001 --des Exp --use_multi_scale False --small_kernel_merged False --type_model 2 --num_extract_blocks 1 --num_memory 1

###################################################################################################

 python -u run.py --is_training 1 --model_id heat2 --model MetaTCN --root_path ./all_six_datasets/heat/ --data_path heath2.csv --data custom --features M --seq_len 12 --pred_len 6 --label_len 0 --ffn_ratio 8 --patch_size 8 --patch_stride 4 --num_blocks 1 --large_size 51 --small_size 5 --dims 256 256 256 256 --head_dropout 0.0 --enc_in 8 --dropout 0.3 --itr 1 --train_epochs 20 --batch_size 256 --patience 20 --learning_rate 0.0001 --des Exp --use_multi_scale False --small_kernel_merged False --type_model 2 --num_extract_blocks 1 --num_memory 1

 python -u run.py --is_training 1 --model_id heat2 --model MetaTCN --root_path ./all_six_datasets/heat/ --data_path heath2.csv --data custom --features M --seq_len 24 --pred_len 12 --label_len 0 --ffn_ratio 8 --patch_size 8 --patch_stride 4 --num_blocks 1 --large_size 51 --small_size 5 --dims 256 256 256 256 --head_dropout 0.0 --enc_in 8 --dropout 0.3 --itr 1 --train_epochs 20 --batch_size 256 --patience 20 --learning_rate 0.0001 --des Exp --use_multi_scale False --small_kernel_merged False --type_model 2 --num_extract_blocks 1 --num_memory 1

 python -u run.py --is_training 1 --model_id heat2 --model MetaTCN --root_path ./all_six_datasets/heat/ --data_path heath2.csv --data custom --features M --seq_len 38 --pred_len 18 --label_len 0 --ffn_ratio 8 --patch_size 8 --patch_stride 4 --num_blocks 1 --large_size 51 --small_size 5 --dims 256 256 256 256 --head_dropout 0.0 --enc_in 8 --dropout 0.3 --itr 1 --train_epochs 20 --batch_size 256 --patience 20 --learning_rate 0.0001 --des Exp --use_multi_scale False --small_kernel_merged False --type_model 2 --num_extract_blocks 1 --num_memory 1

##################################################################################################

 python -u run.py --is_training 1 --model_id heat3 --model MetaTCN --root_path ./all_six_datasets/heat/ --data_path heath3.csv --data custom --features M --seq_len 12 --pred_len 6 --label_len 0 --ffn_ratio 8 --patch_size 8 --patch_stride 4 --num_blocks 1 --large_size 51 --small_size 5 --dims 256 256 256 256 --head_dropout 0.0 --enc_in 8 --dropout 0.3 --itr 1 --train_epochs 20 --batch_size 256 --patience 20 --learning_rate 0.0001 --des Exp --use_multi_scale False --small_kernel_merged False --type_model 2 --num_extract_blocks 1 --num_memory 1

 python -u run.py --is_training 1 --model_id heat3 --model MetaTCN --root_path ./all_six_datasets/heat/ --data_path heath3.csv --data custom --features M --seq_len 24 --pred_len 12 --label_len 0 --ffn_ratio 8 --patch_size 8 --patch_stride 4 --num_blocks 1 --large_size 51 --small_size 5 --dims 256 256 256 256 --head_dropout 0.0 --enc_in 8 --dropout 0.3 --itr 1 --train_epochs 20 --batch_size 256 --patience 20 --learning_rate 0.0001 --des Exp --use_multi_scale False --small_kernel_merged False --type_model 2 --num_extract_blocks 1 --num_memory 1

 python -u run.py --is_training 1 --model_id heat3 --model MetaTCN --root_path ./all_six_datasets/heat/ --data_path heath3.csv --data custom --features M --seq_len 38 --pred_len 18 --label_len 0 --ffn_ratio 8 --patch_size 8 --patch_stride 4 --num_blocks 1 --large_size 51 --small_size 5 --dims 256 256 256 256 --head_dropout 0.0 --enc_in 8 --dropout 0.3 --itr 1 --train_epochs 20 --batch_size 256 --patience 20 --learning_rate 0.0001 --des Exp --use_multi_scale False --small_kernel_merged False --type_model 2 --num_extract_blocks 1 --num_memory 1

##################################################################################################

 python -u run.py --is_training 1 --model_id heat4 --model MetaTCN --root_path ./all_six_datasets/heat/ --data_path heath4.csv --data custom --features M --seq_len 12 --pred_len 6 --label_len 0 --ffn_ratio 8 --patch_size 8 --patch_stride 4 --num_blocks 1 --large_size 51 --small_size 5 --dims 256 256 256 256 --head_dropout 0.0 --enc_in 8 --dropout 0.3 --itr 1 --train_epochs 20 --batch_size 256 --patience 20 --learning_rate 0.0001 --des Exp --use_multi_scale False --small_kernel_merged False --type_model 2 --num_extract_blocks 1 --num_memory 1

 python -u run.py --is_training 1 --model_id heat4 --model MetaTCN --root_path ./all_six_datasets/heat/ --data_path heath4.csv --data custom --features M --seq_len 24 --pred_len 12 --label_len 0 --ffn_ratio 8 --patch_size 8 --patch_stride 4 --num_blocks 1 --large_size 51 --small_size 5 --dims 256 256 256 256 --head_dropout 0.0 --enc_in 8 --dropout 0.3 --itr 1 --train_epochs 20 --batch_size 256 --patience 20 --learning_rate 0.0001 --des Exp --use_multi_scale False --small_kernel_merged False --type_model 2 --num_extract_blocks 1 --num_memory 1

 python -u run.py --is_training 1 --model_id heat4 --model MetaTCN --root_path ./all_six_datasets/heat/ --data_path heath4.csv --data custom --features M --seq_len 38 --pred_len 18 --label_len 0 --ffn_ratio 8 --patch_size 8 --patch_stride 4 --num_blocks 1 --large_size 51 --small_size 5 --dims 256 256 256 256 --head_dropout 0.0 --enc_in 8 --dropout 0.3 --itr 1 --train_epochs 20 --batch_size 256 --patience 20 --learning_rate 0.0001 --des Exp --use_multi_scale False --small_kernel_merged False --type_model 2 --num_extract_blocks 1 --num_memory 1

##################################################################################################